server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST_IP:localhost}:${MYSQL_HOST_PORT:3306}/${MYSQL_HOST_DB:hzq_wiki}?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: ${MYSQL_HOST_USERNAME:root}
    password: ${MYSQL_HOST_PASSWORD:root}
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  security:
    user:
      name: admin
      password: admin

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.hzqing.admin.model
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件 在DruidConfig中配置
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  # 加载全局的配置文件
#  ##configLocation: classpath:mapper/mybatis-config.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.hzqing.admin.model
  type-enums-package: com.hzqing.admin.model.enums.*


hzq:
  druid:
    username: root
    password: root
  fs:
    path: ${WIKI_FS:/tmp/fs/}
