server:
  port: 8080

debug: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hzq_wiki
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.hzqing.admin
  # 配置mapper的扫描，找到所有的mapper.xml映射文件 在DruidConfig中配置
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  # configLocation: classpath:mapper/mybatis-config.xml


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

hzq:
  druid:
    username: root
    password: root